### ISSUE TITLE
Add support for PGN 127257

### ISSUE THREAD

**Issue by sarfata** [ttlappalainen/NMEA2000#10]
It would be great to have support for PGN 127257 so we can transmit and receive attitude messages (heel/pitch/roll).

[It is documented in Canboat](https://github.com/canboat/canboat/blob/master/analyzer/pgn.h#L1573):

````
{ "Attitude", 127257, true, 7, 0,
  { { "SID", BYTES(1), 1, false, 0, "" }
  , { "Yaw", BYTES(2), RES_RADIANS, true, "rad", "" }
  , { "Pitch", BYTES(2), RES_RADIANS, true, "rad", "" }
  , { "Roll", BYTES(2), RES_RADIANS, true, "rad", "" }
  , { 0 }
  }
}
````

It would be good to know what is the reference framework too. I am guessing Yaw is relative to true north. Not sure about pitch and roll.

**Comment by ttlappalainen** [comment]
Hi,

No Idea. Do I add it and try with NMEA Reader, what it shows?

Timo

28.6.2016, 13:49, Thomas Sarlandie kirjoitti:

**Comment by sarfata** [comment]
That would be great. I think if someone could capture data from a sensor that sends them (I think some of the Airmar wind sensors send that information) that would be great too.

**Comment by ttlappalainen** [comment]
Hi,

Yaw could be also relative to  your course over water. For aircrafts it 
has been defined (at least on some referencies) angle between your 
course over air.
pitch = positive, when your bow rises
roll = positive, when tilted right

28.6.2016, 13:49, Thomas Sarlandie kirjoitti:

**Comment by ttlappalainen** [comment]
I just added attitude PGN 127257. I could only test it with NMEA Reader. It also showed Yaw as negative value, so it may be defined as I mentioned in similar ways as in aircrafts as an angle between vessel course over water.

**Comment by sarfata** [comment]
Thanks. I will try with my Raymarine i70 but I doubt it will be supported.
