### ISSUE TITLE
WindMonitor send True Wind

### ISSUE THREAD

**Issue by melucas** [ttlappalainen/NMEA2000#110]
Hello,

I have the WindMonitor working with my Duo and I can see that Apparent wind being updated on my RayMarine MDF.

I would like to also send the True wind speed and direction.

I tried updating the SendN2kWind method's SetN2kWindSpeed function call by setting the WindReference value.  I have tried the True values (N2kWind_True_North, N2kWind_True_boat, N2kWind_True_water) and the Magnetic value (N2kWind_Magnetic).  None of those update my MDF's true wind speed and direction.

How do I set the true wind speed and direction?

Thank you,
Michael

**Comment by ttlappalainen** [comment]
The setting should be right. But note that MFD:s has setting, what you want to show. So if you have selected to show Apparent Wind and it is getting true wind from bus, it can calculate Apparent Wind from your COG/SOG. Have you checked that?

**Comment by melucas** [comment]
Yes, I think the might be the issue.  I don't have any speed or course information on my dev bus.  I will do some more testing once the boat is back in the water and the mast is up.
