### ISSUE TITLE
CAN bus just receive 8 Byte, this lib how to NMEA2000 message？

### ISSUE THREAD

**Issue by craigtao** [ttlappalainen/NMEA2000#116]
I have a question，

CAN bus just receive 8 Byte, this lib how to NMEA2000 message？

this class ActisenseReader ？

craig

**Comment by ttlappalainen** [comment]
See the example codes like ActisenseListener. Example DataDisplay2 just catches several messages and translates them to clear text to serial monitor. Take also look into the document https://github.com/ttlappalainen/NMEA2000/blob/master/Documents/NMEA2000_library_reference.pdf and follow the sample to make TemperatureMonitor. It may help you undestand NMEA2000 and library better.

**Comment by craigtao** [comment]
ok，thank you，

Today I read the source code，

A little understand the principle of processing
N2K_NO_ISO_MULTI_PACKET_SUPPORT

**Comment by ttlappalainen** [comment]
This is if you desperately try to run library on low RAM systems like Uno and need to save RAM. Use systems enough RAM like Teensy 3.2 or higher, ESP32 or Due and library with default definitions. Disabling any feature causes that device is not certification ready anymore.

**Comment by craigtao** [comment]
thank you

**Comment by craigtao** [comment]
Teensy 3.2 and MCP2515 or MCP2551 can run this NMEA2000 lib？

**Comment by ttlappalainen** [comment]
It is possible, but do not see any reason why. Teensy internal CAN is better than MCP2515. Note also that MCP2515 and MCP2551 are not comparable, since one is controller and other is tranceiver.
