### ISSUE TITLE
MCP2515 and receive mask and filter (Arduino Uno)

### ISSUE THREAD

**Issue by olliiiver** [ttlappalainen/NMEA2000#143]
Hi.

Thanks for providing a library for the NMEA 2000 bus.

I tried to use an atmega328p (Arduino Uno). Why? Because pdip package provides easy soldering.

I was able to use the library for sending data to the bus: 

```
// set N2K_NO_HEARTBEAT_SUPPORT, N2K_NO_GROUP_FUNCTION_SUPPORT
#define SlowDataUpdatePeriod 1000
void loop() {
  SendN2kSlowData();
// NMEA2000.ParseMessages();
}
void SendN2kSlowData() {
  static unsigned long SlowDataUpdated=millis();
  tN2kMsg N2kMsg;
  if (SlowDataUpdated+SlowDataUpdatePeriod<millis()) {
    SlowDataUpdated=millis();
    SetN2kFluidLevel(N2kMsg, 1, N2kft_Fuel, 50, 60);
    NMEA2000.SendMsg(N2kMsg);
  }
}
```

Also I was trying to receive data by using minimal version of DataDisplay2, but without any luck. Maybe the bus is too crowded. Seems the loop gets stuck in NMEA2000.ParseMessages(). Without parsing any messages sending works.

Has somebody get this to work on an Arduino Uno?

Would it help to set a receive filter for only messages I need (a feature from the MCP2515)?

**Comment by ttlappalainen** [comment]
Please read https://github.com/ttlappalainen/NMEA2000#memory-requirements. Also check issue https://github.com/ttlappalainen/NMEA2000/issues/20.

Filtering does not help and I do not support that on my library.

The biggest problem is that UNO just does not have enough memory. There is no sense to take any headache with these small memory devices, when there are devices like Teensy 3.x and ESP32 available for nearly same or even cheaper price.
