### ISSUE TITLE
custom PGN sending frequency Q

### ISSUE THREAD

**Issue by virtuvas** [ttlappalainen/NMEA2000#172]
Timo,

quick Qs:

custom PGN single frame, teensy3.5 sending  and Due+LCD receiving (I know I have to switch, but cannot now!)

managed to have decent speed down to 20ms, will probably settle to 50 as it reports position of stabiliser fins which swipe left to right in 1.3sec, and want a fast refresh to be able to visualise what's going on (debugging code mainly)
Q: is there a problem using such speeds? other PGNs seem to be making it okay main delay is the crappy LCD I'm using.

another custom PGN again single frame is now sent every 500ms but honestly it may be 2 or more mins before any value changes making it worth sending. Receiver is again the same Due custom box with the LCD.
Q: Is it better policy to send at set intervals and sort out if I take actions AFTER reading the PGN on the receiving end
or 
is it better to only send when there's something new to send and thus avoid the extra burden and load on bus and mainly the Due receiving the info...
I'm thinking of going on the second route tbh.

your views welcomed!

cheers

V.

**Comment by ttlappalainen** [comment]
Sorry for delay.

50 ms is not problem for CAN bus.

Send policy depends of your purpose. If you send message only when something happens, how do you know that sender has not dead? Or when you turn on your listener, how do you know the current state. One way is that listener request status message, when it turns on and sender always sends it when it will be turned on. Also you can use heartbeat of sender to check that it is alive.

Periodic messages are always required, when it is critical to know that sender is alive. E.g. heading is very critical and autopilot has to alarm rather immediately, if it has been lost.

Easiest is to send message with some period. 5-60 sec period means nothing on total bus traffic and it is much easier to handle than make request-respond logic even that is available on library.
