### ISSUE TITLE
PGN127489 parsing warning flags?

### ISSUE THREAD

**Issue by virtuvas** [ttlappalainen/NMEA2000#199]
happy new year all,

have managed successfully to set warning flags for low oil pressure, overheat, whatever. That's fine, Garmins all come up with the warning screen saying which engine and what type of error is there and I can turn it off from each device/MFD. 
For example the one below is low oil pressure warning:

`     SetN2kEngineDynamicParam(N2kMsg, EngineInst, OilPressureB, EngineOilTempB, CoolantTempB, AltVoltB, N2kDoubleNA, 
                               EngineHoursB, SeawaterPressureB, N2kDoubleNA, N2kInt8NA, N2kInt8NA, 0, 0, 1);
`

and the following is coolant flow warning:

`      SetN2kEngineDynamicParam(N2kMsg, EngineInst, OilPressureB, EngineOilTempB, CoolantTempB, AltVoltB, N2kDoubleNA, 
                               EngineHoursB, SeawaterPressureB, N2kDoubleNA, N2kInt8NA, N2kInt8NA, 0,0,0,0,0,0,0,1);`

maybe rough, but works :-)

Now the problem I have is that I cannot figure out how to parse that!
there are 24 bool options btw, how do I reach them when analysing the PGN??
I need overheat, low oil press, coolant flow and general error.

edit to say, that yes, I can see the structure on N2kMessages.cpp but I'm at loss how you stuff the 3 boolean groups engineStatus1P1, engineStatus1P2 and engineStatus2 in between EngineFuelPress and EngineLoad.

ideas?

cheers

V.

**Comment by ttlappalainen** [comment]
I updated the library. Now you can do easily:
```
    tN2kEngineDiscreteStatus1 Status1;
    Status1.Bits.LowOilLevel=1;
    Status1.Bits.OverTemperature=1;
    SetN2kEngineDynamicParam(N2kMsg,0,656000,CToKelvin(86.3),CToKelvin(82.1),14.21,5.67,hToSeconds(2137.55),N2kDoubleNA,N2kDoubleNA,N2kInt8NA,N2kInt8NA,Status1);
```

and

```
   ...
  tN2kEngineDiscreteStatus1 Status1;
  tN2kEngineDiscreteStatus2 Status2;
  if (ParseN2kPGN127489(N2kMsg,EngineInstance,EngineOilPress,EngineOilTemp,EngineCoolantTemp,
                                 AltenatorVoltage,FuelRate,EngineHours,
                                 EngineCoolantPress,EngineFuelPress,
                                 EngineLoad,EngineTorque,Status1,Status2) ) {
...
   if ( Status1.Bits.OverTemperature ) ...

```
I forgot alias for ParseN2kPGN127489

**Comment by virtuvas** [comment]
thanks Timo,

there are 3 sets of bools though! best if you do the last one as well!

V.

**Comment by virtuvas** [comment]
and I guess means that lib will fail now unless you add the parameters in both Setting and Parsing, right?

**Comment by ttlappalainen** [comment]
No, there are compatible alias also.
