### ISSUE TITLE
Fail to compile on Fedora because of SIGSTKSZ sysconf (_SC_SIGSTKSZ)

### ISSUE THREAD

**Issue by fulup-bzh** [ttlappalainen/NMEA2000#323]
Try a quick compile on Fedora, where it fail on SIGSTKSZ while this define is present inside signal.h file. with following code
```
# undef SIGSTKSZ
# define SIGSTKSZ sysconf (_SC_SIGSTKSZ)
```
Forcing SIGSTKSZ in catch.hpp hide the issue.

stderr
```
/home/fulup/Workspace/CanBus/NMEA2000/third-party/catch/catch.hpp:6491:33: error: size of array ‘altStackMem’ is not an integral constant-expression
 6491 |         static char altStackMem[SIGSTKSZ];
```

**Comment by Andrei-Errapart** [comment]
See https://github.com/ttlappalainen/NMEA2000/pull/328

Hopefully merged soon.

**Comment by ttlappalainen** [comment]
Merged now!

**Comment by fulup-bzh** [comment]
I still have the error on Fedora-37
