### ISSUE TITLE
Two esp32 (m5atom) devices see each other but not others

### ISSUE THREAD

**Issue by mgrouch** [ttlappalainen/NMEA2000#331]
I’m using your library on esp32 with m5atom.
Somehow
two esp32 (m5atom) devices see each other but not others. 
And vice versa 2 other devices (non m5atom based) see each other’s messages but
not m5atom ones.  
I suspect some can clock or rate is by default different on m5atom with 
CAIS3050G. So they can talk to each other but not the others. 
I’m lost at this point.

thanks!

**Comment by ttlappalainen** [comment]
Either there is CANH/CANL mixed or for some reason m5atom boards has wrong baud rate. Easiest is to swap CANH/CANL wires on CAIS3050G. If that does not help modify NMEA2000_esp32 speed setting on constructor: speed(CAN_SPEED_250KBPS).

CAIS3050G is just tranceiver and isolation module and should no have way to change CAN clock.

**Comment by mgrouch** [comment]
I just swapped H and L on both m5 atoms and everything started working!
Jeez. I spent two days trying to isolate it in software. Thinking it’s software issue. 
My NMEA cable when I cut it came with unconventional coloring. So I connected blue in whatever was marked blue in m5atom. 

Thanks for getting back and solving it so quickly. !

**Comment by ttlappalainen** [comment]
These boxes are traditionally made for CAN and so they do not follow N2k colouring.

**Comment by mgrouch** [comment]
So by swapping wires I effectively can have 2 somewhat independent logical buses on one physical CAN bus? Are there bad side effects?
Just curious…

Thanks

**Comment by ttlappalainen** [comment]
No. It will cause errors for both. It works unpredictable and gets worse with more traffic.

**Comment by mgrouch** [comment]
Ok. Thanks
