### ISSUE TITLE
Resolve dependencies for platformio package

### ISSUE THREAD

**Issue by alexg-k** [ttlappalainen/NMEA2000#334]
First of all, thanks for this awesome library!

Now, adding
```
lib_deps = 
ttlappalainen/NMEA2000-library@^4.18.7
````
to my projects `platformio.ini` results in compilation errors. I have to manually add
```
lib_deps = 
        seeed-studio/CAN_BUS_Shield@^2.3.3
	ttlappalainen/NMEA2000_mcp@^1.1.2
	ttlappalainen/NMEA2000-library@^4.18.7
````
to resolve some issues. Can you please give the dependencies to [here](https://registry.platformio.org/libraries/ttlappalainen/NMEA2000_mcp/insights/dependencies), so the right dependencies will be installed automatically?

Though there are further issues integrating your lib in my platformio project, but the issue could also be located in the CAN_BUS_Shield library:
````
[...]
Scanning dependencies...
Dependency Graph
|-- CAN_BUS_Shield @ 2.3.3
|-- NMEA2000-library @ 4.18.7
|-- NMEA2000_mcp @ 1.1.2
Building in release mode
Compiling .pio/build/uno/src/main.cpp.o
Compiling .pio/build/uno/libdfd/NMEA2000_mcp/NMEA2000_mcp.cpp.o
In file included from .pio/libdeps/uno/NMEA2000-library/src/NMEA2000_CAN.h:304:0,
                 from src/main.cpp:22:
.pio/libdeps/uno/NMEA2000_mcp/NMEA2000_mcp.h:45:11: error: cannot declare field 'tNMEA2000_mcp::N2kCAN' to be of abstract type 'MCP_CAN'
   MCP_CAN N2kCAN;
           ^~~~~~
In file included from .pio/libdeps/uno/NMEA2000-library/src/NMEA2000_CAN.h:283:0,
                 from src/main.cpp:22:
.pio/libdeps/uno/CAN_BUS_Shield/src/mcp_can.h:55:7: note:   because the following virtual functions are pure within 'MCP_CAN':
 class MCP_CAN
       ^~~~~~~
[...]
````

**Comment by ttlappalainen** [comment]
You should use mcp_can under my git, not others, if they has not been validated.

**Comment by alexg-k** [comment]
I am unable to find a `mcp_can` repo under your username on github or on the platformio registry.

**Comment by ttlappalainen** [comment]
https://github.com/ttlappalainen/CAN_BUS_Shield

**Comment by alexg-k** [comment]
I see, thx! The repo has a platformio library file, but is not listed on the platformio registry under your username. Could you register it over there?

**Comment by alexg-k** [comment]
PR #335 fixes the integration of this library in a platformio project.

Please Note: I am not sure, that this dependency stack is true for every platformio project using this library.

**Comment by ttlappalainen** [comment]
I cancelled your PR. It will not work as you did it.

**Comment by alexg-k** [comment]
I understand. In case somebody else wants to use your library with PlatformIO and my hardware setup (Arduino MKR Wi-Fi 1010 & MKR Can Shield), I ended up with these dependencies: 
````
lib_deps = 
	;ttlappalainen/CAN_BUS_Shield@^1.20 ; <-maybe in the future?
	https://github.com/ttlappalainen/CAN_BUS_Shield.git
	ttlappalainen/NMEA2000_mcp@^1.1.2
	ttlappalainen/NMEA2000-library@^4.18.7
````

**Comment by ttlappalainen** [comment]
Why do you need those lib_deps. I have PlatformIO projects for different MCU:s and never used lib_deps. You can simply copy NMEA2000, CAN_BUS_Shield and NMEA2000_mcp under you project lib. Or what is even better you copy CAN_BUS_Shield and NMEA2000_mcp under lib_MKR folder and add that folder as library in platformio.ini. Then you can have own definition for e.g.. ESP32 for same project and use lib_ESP.

Be aware that if you modify library files, you need to redo modification for every library update.
