### ISSUE TITLE
Example DeviceAnalyzer does not compile

### ISSUE THREAD

**Issue by red8o** [ttlappalainen/NMEA2000#345]
I get an error when trying to use getManufacturerInformation(): NMEA2000.h appears to be missing this code segment

```c
      /** \brief Get the manufacturer information from the configuration 
       * information of this device*/
      virtual const char * GetManufacturerInformation() const { return 0; }
```

somewhere close to line 590, I suppose.

**Comment by ttlappalainen** [comment]
It had probably dropped during documentation. I'll add it back below line // Configuration information
