### ISSUE TITLE
Question about using a tMsgHandler class

### ISSUE THREAD

**Issue by schwinn** [ttlappalainen/NMEA2000#350]
Hi,

I've a written a tMsgHandler class, which monitors a serial port for GPS data and sending a PGN 129029, 129026 and 126992 message every second. 

Everything works fine so far, but once or twice a day some frames of the PGN 129029 Fast Packet message arrive exactly one second later. I notice this, because I monitor the fast packet messages which are not completed in time (750ms timeout). I am sure there is no blocking inside the loop, as i monitor the duration of the loop. It seems that the remaining frames are only sent when a new PGN 129029 message is sent. In my opinion, the buffered frames should be sent when calling ParseMessages() in the main loop.

Is this by design and caused by using a class?

I'm using a Teensy 4.0 microcontroller und platformio. 

Thanks,
Thorsten

**Comment by ttlappalainen** [comment]
I do not understand you system. tNMEA2000::tMsgHandler is for monitor messages from NMEA2000 bus not from serial. If you read NMEA0183 messages from serial port, I prefer to use NMEA0183 library fo that.

If you sent messages to N2k bus I prefer to send them on own "task" and using tN2kSyncScheduler. This ensures PGN:s will be sent periodically and synctonized. Collect necessary data for you PGN:s on other "task". See example TemperatureMonitor.

And remember that your loop should not have any delays. Also there are different kind of tasking systems, but you must be careful with them - they may not work properly with library.

**Comment by schwinn** [comment]
Hi Timo,

please forget everything I asked about tMsgHandler. I kept looking for the problem and have now found something. 

It seems the problem is in NMEA2000_Teensyx. In rare cases, the ISR routine flexcan_interrupt() stops sending packets even though there is still data of the appropriate priority in the txRing. The remaing data is sent out, when new data for this MB/priority is sent by CANSendFrame. In my case, this means new GPS Data in 1000ms interval, which is the only data in priority 3 I sent out.

I have writte a small N2K library in golang and I have a 750ms timeout for fastpackets. This means, my fastpacket buffer is cleared after 750ms, if it has not received all data. Below you can find the log if this rare event and it shows the 1 second gap between frame 2 and 3. 

```
[n2k] FastPacket - clear buffer - Source 40 - PGN 129029 - SequenceID 0 - Key 6593446017029
[n2k] FastPacket - Length 43 - Total Frame 7 - Last Frame 2 - Last Received 2023-10-12T21:58:00.09097899+02:00
[n2k] FastPacket - Frame 0 - Length 6 - Received 2023-10-12T21:58:00.090834991+02:00
[n2k] FastPacket - Frame 1 - Length 7 - Received 2023-10-12T21:58:00.090925991+02:00
[n2k] FastPacket - Frame 2 - Length 7 - Received 2023-10-12T21:58:00.09097899+02:00
[n2k] FastPacket - clear buffer - Source 40 - PGN 129029 - SequenceID 0 - Key 6593446017029
[n2k] FastPacket - Length 0 - Total Frame 0 - Last Frame 6 - Last Received 2023-10-12T21:58:01.096315882+02:00
[n2k] FastPacket - Frame 3 - Length 7 - Received 2023-10-12T21:58:01.090654928+02:00
[n2k] FastPacket - Frame 4 - Length 7 - Received 2023-10-12T21:58:01.096194883+02:00
[n2k] FastPacket - Frame 5 - Length 7 - Received 2023-10-12T21:58:01.096267883+02:00
[n2k] FastPacket - Frame 6 - Length 7 - Received 2023-10-12T21:58:01.096315882+02:00
```

After many tests and studying the code, I noticed that the writeIFLAGBit function has been changed in the FlexCAN_T4 library. The logical or was removed when setting the register.

This is from FlexCAN_T4.
```
FCTP_FUNC void FCTP_OPT::writeIFLAGBit(uint8_t mb_num) { // bugfix by bsundahl1
  if ( mb_num < 32 ) FLEXCANb_IFLAG1(_bus) = (1UL << mb_num);
  else FLEXCANb_IFLAG2(_bus) = (1UL << (mb_num - 32));
}
```

And this is from NMEA2000_Teensyx.
```
void tNMEA2000_Teensyx::writeIFLAGBit(uint8_t mb_num) {
  if ( mb_num < 32 ) {
    FLEXCANb_IFLAG1(bus) |= (1UL << mb_num);
  } else {
    FLEXCANb_IFLAG2(bus) |= (1UL << (mb_num - 32));
  }
}
```
I have now removed the logical or in the NMEA2000_Teensyx as a test and after more than a week the problem no longer occurs. It seems the writeIFLAGBit is clearing the wrong flag in rare cases and the TX_INACTIVE interrupt is not being generated, which is stopping the ISR from sending the rest of txRing buffer for this priority. 

The NXP documentation states this about the IFLAG register on 44.9.12.
```
This register defines the flags for 32 Message Buffer interrupts and FIFO interrupts. It
contains one interrupt flag bit per buffer. Each successful transmission or reception sets
the corresponding IFLAG1 bit. If the corresponding IMASK1 bit is set, an interrupt will
be generated. The Interrupt flag must be cleared by writing it to '1'. Writing '0' has no
effect.
```
So writing the bit without logical or seems the correct way.

What do you think?

Best regards,
Thorsten

**Comment by ttlappalainen** [comment]
Sounds logic. Should only clear bit handled. With "or" one may clear some bit  of other buffer waiting for handling.

This is unfortunate that I could not use FlexCAN_T4. Older Teensy code uses FlexCAN and that leaded the situation that they never too my recommedations for NMEA2000 and caused that I had to publish my own version causing more confusing.

**Comment by schwinn** [comment]
I only looked at the flexcan_T4 library code to maybe find the problem. I had previously suspected a flexcan problem, which is described in the errata. But that did not lead to any improvement. 

Will you change the function writeIFLAGBit in NMEA2000_Teensyx in the future?

**Comment by ttlappalainen** [comment]
Yes. I'll run some tests first with my Simulator, which I can use to fill bus.

**Comment by ttlappalainen** [comment]
I just updated NMEA2000_Teensyx driver
