### ISSUE TITLE
N2K_NO_HEARTBEAT_SUPPORT break NMEA2000

### ISSUE THREAD

**Issue by trixpan** [ttlappalainen/NMEA2000#357]
Using

```
#define N2K_NO_HEARTBEAT_SUPPORT 1 
```

Causes to error compilations in 

https://github.com/ttlappalainen/NMEA2000/blob/9a6057b4b581a629fc039af70f8eeaafec056520/src/NMEA2000.cpp#L1201

**Comment by trixpan** [comment]
@ttlappalainen FYI

**Comment by ttlappalainen** [comment]
Fixed on 22.01.2024 update.
