### ISSUE TITLE
void SetHeartbeatInterval(unsigned long interval, bool SetAsDefault=true, int iDev=-1) __attribute__ ((deprecated));

### ISSUE THREAD

**Issue by sboicu** [ttlappalainen/NMEA2000#375]
Hello.

Do you know about this warning? How can it be fixed?
I am using the latest Arduino IDE 2.2.1 and latest esp32-arduino-core 2.0.14
\Arduino\libraries\NMEA2000\src/NMEA2000.h:2383:10: note: declared here
     void SetHeartbeatInterval(unsigned long interval, bool SetAsDefault=true, int iDev=-1) __attribute__ ((deprecated));
I am allowed to compile and do my things with the sketch, but would be nice not to have any warnings, who knows in the future what can they bring.

all the best

**Comment by ttlappalainen** [comment]
If you are not calling that function, it should now warn you. If you call it, you should instead as documented use function SetHeartbeatIntervalAndOffset. On the other hand I do not see why you should touch HB settings - defaults are OK in 99.9%.

I'll remove interface some day.
