### ISSUE TITLE
AddGroupFunctionHandler examples

### ISSUE THREAD

**Issue by dansonamission** [ttlappalainen/NMEA2000#392]
Hey, are there any example sketches using AddGroupFunctionHandler?

I am trying to monitor PGN 126208 for data instance changes but struggling. Such as changing the data instance of a fluid sender. I have the request group function codes etc.

Any help would be much appreciated.
Thanks

**Comment by ttlappalainen** [comment]
There is no examples except in N2kGroupFunctionDefaultHandlers. I use different message handling and general group function handler, but that method is not published - maybe some day in future.

Data instance can be changed only by Write Fields Group Function. There you need to parse selection pairs ( like in e.g., tN2kGroupFunctionHandlerForPGN60928::HandleRequest ) and if they match, you parse fields to be set. Note that selection fields can be in any order. Then you need to response with Write Fields Reply, if all fields are OK or Acknowledge with each field status ( like e.g., in tN2kGroupFunctionHandlerForPGN60928::HandleCommand), if you can not comply write. You can start building Acknowledge with SetStartAcknowledge. 

I do not know should broacast Write Fields Group Function be accepted or not and either do not know should you reply with Write Fields Reply or Acknowledge to broadcast.

**Comment by dansonamission** [comment]
Thanks for your response, we are familiar with NMEA2000 it’s the library we are stuck with. 

Where should I be using AddGroupFunctionHandler() trying to use it in a sketch but doesn’t matter what I put in the () it won’t compile. Should we be putting it in the library instead within NMEA open?

**Comment by ttlappalainen** [comment]
You need to inherit own handler from tN2kGroupFunctionHandler as done in N2kGroupFunctionDefaultHandlers. Then you can register it in setup:
```
class tN2kMyPGNGroupFunctionHandler  : public tN2kGroupFunctionHandler {
...
};

void setup() {
...
  NMEA2000.AddGroupFunctionHandler(new tN2kMyPGNGroupFunctionHandler(&NMEA2000));
...
}
```

**Comment by dansonamission** [comment]
Do you know how actisense reader works for changing the data instance as it doesn't call the group function handler?

11:41:07.677 -> 171242 : Pri:3 PGN:126208 Source:2 Dest:3 Len:11 Data:5,11,F2,1,FF,1,1,1,0,1,0
11:41:07.677 -> 171243 : Pri:3 PGN:126208 Source:3 Dest:2 Len:7 Data:2,11,F2,1,6,1,F0

Your simulator calls the group function when a request or command is sent but can't work out how to use the simulator to request or command a data instance change.

**Comment by ttlappalainen** [comment]
Now I could not follow you. How do you change data instance with Actisense Reader?

Where the messages came from? There was change request and NAK response.

Simulator does not yet have direct method for sending read or write fields group function like request and command groupfunctions undet Tools-NMEA2000 commands-Group function. But under Tools-NMEA2000 commands-Any Message you can send to bus what ever you like. E.g., request PGN 127505 data instance to be changed to 1 write line (or copy-paste)
PGN:126208 5,11,F2,1,FF,1,1,1,0,1,1
to data box and then activate line by click over line -> it changes red. Then press button "Send".
Or yoy can also have
PGN:126208 Source:2 Dest:3 5,11,F2,1,FF,1,1,1,0,1,1

**Comment by dansonamission** [comment]
Within Actisense NMEA reader you can change the data instance by right-clicking on the PGN within the data view.

This is what it transmits but does not call the Group function handler for PGN 126208. The simulator does call my group function when doing a request.

![image](https://github.com/ttlappalainen/NMEA2000/assets/1254672/2b810980-7020-4002-b036-97b90f22490a)

**Comment by dansonamission** [comment]
:)

Am I correct in thinking..... because the group handler functions are only handling commands and requests, it is ignoring the 'write field' option?

This is what Actisense EBL Reader shows.

![image](https://github.com/ttlappalainen/NMEA2000/assets/1254672/fe5b431a-ebbb-49cc-8201-0ee50ab742eb)

**Comment by dansonamission** [comment]
I can't find your email address?

Added a writefield function to my group handlers but it's not being called. I see the only examples you have in defaults are commands and requests.

bool tN2kGroupFunctionHandlerForPGN126208::HandleWriteFields(

virtual bool HandleWriteFields(const tN2kMsg &N2kMsg, uint16_t ManufacturerCode, uint8_t IndustryGroup, uint8_t UniqueID, uint8_t NumberOfSelectionPairs, uint8_t NumberOfParameterPairs, int iDev);

**Comment by ttlappalainen** [comment]
See on Simulator Help-About

**Comment by ttlappalainen** [comment]
Did you add to you inherited groupfunction handler function.

    virtual bool HandleWriteFields(const tN2kMsg &N2kMsg,
                                  uint16_t ManufacturerCode, 
                                  uint8_t IndustryGroup, 
                                  uint8_t UniqueID,
                                  uint8_t NumberOfSelectionPairs,
                                  uint8_t NumberOfParameterPairs,
                                  int iDev);

**Comment by dansonamission** [comment]
Yep

![image](https://github.com/ttlappalainen/NMEA2000/assets/1254672/55315f7e-7cb4-47c4-983a-699110e8adc2)


Its still calling the main group function with N2KGroupFunction.cpp

**Comment by ttlappalainen** [comment]
In tN2kGroupFunctionHandler::Handle I have
```
    case N2kgfc_Write:
        if ( tNMEA2000::IsBroadcast(N2kMsg.Destination) ) {
          handled=true;  // We can mark this handled, since write is not allowed to broadcast.
        } else {
          if (ParseReadOrWriteParams(N2kMsg,ManufacturerCode,IndustryGroup,UniqueID,NumberOfSelectionPairs,NumberOfParameterPairs,Propr)) {
            handled=HandleWriteFields(N2kMsg,ManufacturerCode,IndustryGroup,UniqueID,NumberOfSelectionPairs,NumberOfParameterPairs,iDev);
          }
        }
```
So it should work addressed. As I mentioned I am not sure should it accept broadcast - I have not found mention about it, so maybe it should. You can try to change above:
```
    case N2kgfc_Write:
          if (ParseReadOrWriteParams(N2kMsg,ManufacturerCode,IndustryGroup,UniqueID,NumberOfSelectionPairs,NumberOfParameterPairs,Propr)) {
            handled=HandleWriteFields(N2kMsg,ManufacturerCode,IndustryGroup,UniqueID,NumberOfSelectionPairs,NumberOfParameterPairs,iDev);
          }
```

**Comment by dansonamission** [comment]
I tried your suggestion but it still calls the default function and not my custom one.

**Comment by dansonamission** [comment]
The CASE works fine as the data is addressed. It calls this default function and not my custom one.

![image](https://github.com/ttlappalainen/NMEA2000/assets/1254672/56c02952-d502-42c7-9392-bb71409f8fc9)

**Comment by ttlappalainen** [comment]
Your constructor and handler name is wrong. Should be:
tN2kGroupFunctionHandlerForPGN127505(tNMEA2000 *_pNMEA2000) : tN2kGroupFunctionHandler(_pNMEA2000,127505L) {}
You want to handle 127505 not 126208. If someone would call groupfunction handling for 126208, then your class would be called.

**Comment by dansonamission** [comment]
Thanks, that got it working, was getting confused as the PGN that comes through shows 126208
