### ISSUE TITLE
Negative headings from PGN 127250

### ISSUE THREAD

**Issue by steveh57** [ttlappalainen/NMEA2000#40]
In N2KMessages.cpp, ParseN2kPGN127250 returns negative values for headings between 180 and 360.  I think Heading=N2kMsg.Get2ByteDouble(0.0001,Index); needs to change to Get2ByteUDouble or am I misunderstanding something?

**Comment by ttlappalainen** [comment]
You were rigth. Also Deviation and variation parsing were wrong.
