### ISSUE TITLE
Some Library file missing

### ISSUE THREAD

**Issue by erkanrua** [ttlappalainen/NMEA2000#433]
NMEA2000\src/NMEA2000_CAN.h:317:10: fatal error: NMEA2000_mcp.h: No such file or directory
 #include <NMEA2000_mcp.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by ttlappalainen** [comment]
As explained on document, you need to load also NMEA2000_mcp (https://github.com/ttlappalainen/NMEA2000_mcp) and CAN_BUS_shiel (https://github.com/ttlappalainen/CAN_BUS_Shield) libraries.

**Comment by erkanrua** [comment]
Thank you for advice. After two repo installed solved my problem. Which document write it I didn't see. 

Thank you for your help

**Comment by ttlappalainen** [comment]
Did you read the library first page? On bottom it says "... full documentation ..."

![kuva](https://github.com/user-attachments/assets/be77b47e-d6ae-4e31-805e-c4a1563f287c)

Then there is heading "Get your project started" https://ttlappalainen.github.io/NMEA2000/get_started.html
