### ISSUE TITLE
Parse N2kPGN128259 Boat Speed -> error?

### ISSUE THREAD

**Issue by ronzeiller** [ttlappalainen/NMEA2000#74]
Generating PGNs with Kave NMEA Simulator writing to NMEA200 Bus, reading from Bus with NMEA2000 Library PGN 128259 Boat Speed:

Parsing the PGN gives for WaterRefereced and GroundReferenced always the same value.
If there is current set in Simulator then WaterRefereced and GroundReferenced are both the values for GroundReferenced.
In other words WaterRefereced shows actual GroundReferenced value.

In the library in N2kMessages.cpp itself there is:
In  SetN2kPGN128259: twice N2kMsg.Add2ByteUDouble
In  ParseN2kPGN128259: Line 546 --> Get2ByteDouble(0.01,Index)  (without U)

(Is another issue, as it does not make any difference for the values)

**Comment by ttlappalainen** [comment]
Thanks - I am just testing is anybody actually reading anything carefully:) Unfortunate copy-paste issue on NMEA Simulator.

I'll check N2kMessages.cpp too, which one is right - with or without U. I expect with U, but this depends of standard definition. With wrong type error appears example with NA values.

**Comment by ronzeiller** [comment]
:-)
So may be we get a new Version of Kave Simulator? ;-)

**Comment by ttlappalainen** [comment]
Yes, now there is new version.

Also N2kMessages.cpp has been fixed.

**Comment by ronzeiller** [comment]
Fast & Genious :-)
Thank you, it works like a charm now 👍
