### ISSUE TITLE
library.json for Platformio

### ISSUE THREAD

**Issue by ronzeiller** [ttlappalainen/NMEA2000#80]
Hi Timo,

if I understood it right, then it would be possible to install your library in platformio by the built in library manager, including updates. This would be great.
They say a library.json is needed for that.
May be you find some time to have a look at?
http://docs.platformio.org/en/latest/librarymanager/config.html

Thank You!

**Comment by ttlappalainen** [comment]
I'll try to check that some time.

**Comment by ronzeiller** [comment]
Thank you Timo!

![image](https://user-images.githubusercontent.com/12698891/32605334-6210b82a-c551-11e7-95ac-980a018d0969.png)
